// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package tdb

import (
	"database/sql"
)

type Page struct {
	PageID   int32
	ParentID sql.NullInt32
	RouteID  sql.NullInt32
	Label    string
	Data     sql.NullString
}

type Route struct {
	RouteID int32
	Slug    sql.NullString
}
