services:
  mariadb:
    image: mariadb:latest
    container_name: Go-Template-Test
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: gotemp_db
      MARIADB_USER: gotemp_db_u
      MARIADB_PASSWORD: root#root
      MARIADB_ROOT_PASSWORD: root#root
    volumes:
      - ~/Documents/Code/Go/go-template-test/volume:/var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--skip-secure-auth"
    ]

volumes:
  mariadb_data:
    driver: local
